spring:
  datasource:
    url: jdbc:mysql://192.168.3.134:3306/dfans?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: 'lihao'
    password: 'VuW8fzRZ/0MAZOB'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      maxLifetime: 600000
