server:
  port: 8090

spring:
  application:
    name: lagou-service-autodeliver

#注册到Eureka服务中心
eureka:
  client:
    service-url:
      #注册到集群, 逗号拼接
      defaultZone: http://EurekaServerA:8761/eureka,http://EurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true #服务实例中显示ip,而不是主机名
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@ #实例名称,支持自定义

