server:
  port: 8761
spring:
  application:
    name: lagou-cloud-eureka-server #应用名称, 会在eureka中作为服务名称
    # eureka 客户端配置,和server交互, Eureka Server 其实也是一个Client
eureka:
  instance:
    hostname: EurekaServerA #当前实例的主机名
  client:
    service-url: #配置客户端所交互的Eureka Server的地址 8761
      defaultZone: http://EurekaServerB:8762/eureka #如果有更多的节点,逗号拼接即可
    register-with-eureka: true #自己就是server,不需要注册自己,集群模式下改为true,如果需要配置集群,需要修改(新增)自己的主机地址 C:\Windows\System32\drivers\etc
    fetch-registry: true #查询获取注册中心的服务信息,自己就是Server,不需要获取服务信息,默认为true,此处置为false,集群模式下改为true

