spring:
  mail:
    host: email-smtp.ap-southeast-2.amazonaws.com
    port: 587
    username: 'AKIA4KRFSZIY5APNIXPU'
    password: 'BF4UqpSu9U6JgI5uysKJyrikzvvVeKgHPCQ/to9pSIFv'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true