spring:
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    port: 587
    username: {SMTP_USERNAME}
    password: {SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
