

spring:
  application:
    name: lagou-service-autodeliver

#注册到Eureka服务中心
eureka:
  client:
    service-url:
      #注册到集群, 逗号拼接
      defaultZone: http://EurekaServerA:8761/eureka,http://EurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true #服务实例中显示ip,而不是主机名
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@ #实例名称,支持自定义

#针对的被调⽤⽅微服务名称,不加就是全局⽣效 (服务名需要大写, 小写不生效)
LAGOU-SERVICE-RESUME:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略调整

# springboot中暴露健康检查等断点接⼝
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 是否暴露健康接⼝的细节
  endpoint:
    health:
      show-details: always
server:
  port: 8090
