eureka:
  client:
    service-url: # eureka server\u7684\u8DEF\u5F84
      #\u628A eureka \u96C6\u7FA4\u4E2D\u7684\u6240\u6709 url \u90FD\u586B\u5199\u4E86\u8FDB\u6765\uFF0C\u4E5F\u53EF\u4EE5\u53EA\u5199\u2F00\u53F0\uFF0C\u56E0\u4E3A\u5404\u4E2A eurekaserver \u53EF\u4EE5\u540C\u6B65\u6CE8\u518C\u8868
      defaultZone: http://EurekaServerA:8761/eureka,http://EurekaServerB:8762/eureka
  instance:
    #\u4F7F\u2F64ip\u6CE8\u518C\uFF0C\u5426\u5219\u4F1A\u4F7F\u2F64\u4E3B\u673A\u540D\u6CE8\u518C\u4E86\uFF08\u6B64\u5904\u8003\u8651\u5230\u5BF9\u2F7C\u7248\u672C\u7684\u517C\u5BB9\uFF0C\u65B0\u7248\u672C\u7ECF\u8FC7\u5B9E\u9A8C\u90FD\u662Fip\uFF09
    prefer-ip-address: true
    #\u2F83\u5B9A\u4E49\u5B9E\u4F8B\u663E\u793A\u683C\u5F0F\uFF0C\u52A0\u4E0A\u7248\u672C\u53F7\uFF0C\u4FBF\u4E8E\u591A\u7248\u672C\u7BA1\u7406\uFF0C\u6CE8\u610F\u662Fip-address\uFF0C\u65E9\u671F\u7248\u672C\u662FipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
server:
  port: 9999
Spring:
  application:
    name: lagou-cloud-oauth-server
  cloud:
    nacos:
      discovery:
        ################ 配置nacos server地址
        server-addr: http://101.133.163.204:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.133.163.204:3306/oauth2?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    hikari:
      connection-timeout: 10000
      connection-test-query: select now()
      validation-timeout: 3000
      maximum-pool-size: 50
      minimum-idle: 2
      auto-commit: true

mybatis-plus:
  executor-type: batch # batch\u6267\u884C\u5668
  mapper-locations: "classpath:META-INF/mapper/*Mapper.xml"
  configuration:
    default-executor-type: simple # \u9ED8\u8BA4\u914D\u7F6E
    # \u6253\u5370Sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
