server:
  port: 8762
spring:
  application:
    name: lagou-cloud-eureka-server #应用名称, 会在eureka中作为服务名称
    # eureka 客户端配置,和server交互, Eureka Server 起始也是一个Client
eureka:
  instance:
    hostname: EurekaServerB #当前实例的主机名
  client:
    service-url: #配置客户端所交互的Eureka Server的地址 8761,每一个server对于其他server来说,都是client
      # 集群模式下,defaultZone应该指向其他Server
      defaultZone: http://EurekaServerA:8761/eureka
    register-with-eureka: true #自己就是server,不需要注册自己
    fetch-registry: true #查询获取注册中心的服务信息,自己就是Server,不需要获取服务信息,默认为true,此处置为false
