server:
  port: 8080
spring:
  datasource:
    dynamic:
      primary: local
      datasource:
        local:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://101.133.163.204:3306/lagou?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
          username: root
          password: root
          hikari:
            connection-timeout: 10000
            connection-test-query: select now()
            validation-timeout: 3000
            maximum-pool-size: 50
            minimum-idle: 2
            auto-commit: true
  application:
    name: lagou-service-resume
  cloud:
    nacos:
      discovery:
        ################ 配置nacos server地址
        server-addr: http://101.133.163.204:8848
  zipkin:
    base-url: http://101.133.163.204:9411 # zipkin server的请求地址
    sender:
      # web 客户端将踪迹⽇志数据通过⽹络请求的⽅式传送到服务端，另外还有配置
      # kafka/rabbit 客户端将踪迹⽇志数据传递到mq进⾏中转
      type: web
    sleuth:
      sampler:
        # 采样率 1 代表100%全部采集 ，默认0.1 代表10% 的请求踪迹数据会被采集
        # ⽣产环境下，请求量⾮常⼤，没有必要所有请求的踪迹数据都采集分析，对于⽹络包括server端压⼒都是⽐较⼤的，可以配置采样率采集⼀定⽐例的请求的踪迹数据进⾏分析即可
        probability: 1
mybatis-plus:
  executor-type: batch # batch执行器
  mapper-locations: "classpath:META-INF/mapper/*Mapper.xml"
  configuration:
    default-executor-type: simple # 默认配置
    # 打印Sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false

#注册到Eureka服务中心
eureka:
  client:
    service-url:
      #注册到集群, 逗号拼接
      defaultZone: http://EurekaServerA:8761/eureka,http://EurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true #服务实例中显示ip,而不是主机名
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@ #实例名称,支持自定义
    metadata-map:
      hello: world
      isBool: true

#分布式链路追踪
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug
