server:
  port: 9092
spring:
  application:
    name: lagou-cloud-stream-consumer
  cloud:
    stream:
      binders: # \u7ED1\u5B9AMQ\u670D\u52A1\u4FE1\u606F\uFF08\u6B64\u5904\u6211\u4EEC\u662FRabbitMQ\uFF09
        lagouRabbitBinder: # \u7ED9Binder\u5B9A\u4E49\u7684\u540D\u79F0\uFF0C\u2F64\u4E8E\u540E\u2FAF\u7684\u5173\u8054
          type: rabbit # MQ\u7C7B\u578B\uFF0C\u5982\u679C\u662FKafka\u7684\u8BDD\uFF0C\u6B64\u5904\u914D\u7F6Ekafka
          environment: # MQ\u73AF\u5883\u914D\u7F6E\uFF08\u2F64\u6237\u540D\u3001\u5BC6\u7801\u7B49\uFF09
            spring:
              rabbitmq:
                host: 101.133.163.204
                port: 5672
                username: guest
                password: guest
      bindings: # \u5173\u8054\u6574\u5408\u901A\u9053\u548Cbinder\u5BF9\u8C61
        input: # output\u662F\u6211\u4EEC\u5B9A\u4E49\u7684\u901A\u9053\u540D\u79F0\uFF0C\u6B64\u5904\u4E0D\u80FD\u4E71\u6539
          destination: lagouExchange # \u8981\u4F7F\u2F64\u7684Exchange\u540D\u79F0\uFF08\u6D88\u606F\u961F\u5217\u4E3B\u9898\u540D\u79F0\uFF09
          content-type: text/plain # application/json # \u6D88\u606F\u7C7B\u578B\u8BBE\u7F6E\uFF0C\u2F50\u5982json
          binder: lagouRabbitBinder # \u5173\u8054MQ\u670D\u52A1

eureka:
  client:
    service-url:
      defaultZone: http://EurekaServerA:8761/eureka,http://EurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@